name: DeathBan
version: "3.7"
main: com.nokhoon.deathban.PluginMain
description: You need to rest... calm down.
api-version: "1.21.10"
author: "0x0804ac"
commands: 
  respawn:
    description: manages how long a player should wait for respawn.
    usage: /respawn (additional|default|get|set) ...